version: '3'
services:
  db:
    image: postgres:10.5-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  server:
    build: .
    links:
    - db:db
    ports:
    - 8088:8088
    environment:
      DATABASE_URL: 'postgres://postgres:password@db:5432/postgres?sslmode=disable'
      DATA_DIRECTORY: '/go/src/9phum.com/financial-app-backend/'