version: '3'
services:
  db:
    container_name: mycontainername
    image: postgres:10.5-alpine
    ports: 
      - 5433:5433
    environment: 
      POSTGRES_PASSWORD: password
  server:
    build: .
    links:
    - db:db
    ports:
    - "8088:8088"
    environment:
      DATABASE_URL: 'postgres://postgres:password@db:5433/postgres?sslmode=disable'
      DATA_DIRECTORY: '/go/src/9phum.com/financial-app-backend/'